# This is a sample configuration to run a Drupal-instance with Docker-Compose.
# For customization options see: https://docs.docker.com/compose/yml/

drupal:
  build: .
  links:
    - db:mysql
  ports:
    - "80:80"
  volumes:
    - /var/www/html/sites
    - /var/www/private
    - ../monitoring-tools/plugins/check-drupal-cache:/opt/drupal_cache
    - ../monitoring-tools/plugins/check-drupal-codebase:/opt/drupal_codebase
    - ../monitoring-tools/plugins/check-drupal-cron:/opt/drupal_cron
    - ../monitoring-tools/plugins/check-drupal-database:/opt/drupal_database
    - ../monitoring-tools/plugins/check-drupal-extensions:/opt/drupal_extensions
    - ../monitoring-tools/plugins/check-drupal-logging:/opt/drupal_logging
    - ../monitoring-tools/plugins/check-drupal-security:/opt/drupal_security
    - ../monitoring-tools/plugins/check-drupal-status:/opt/drupal_status
    - ../monitoring-tools/plugins/check-drupal-views:/opt/drupal_views
  environment:
    - UPLOAD_LIMIT=20M
    - MEMORY_LIMIT=128M
    - DB_NAME=drupal
    - DB_USER=root
    - DB_PASS=password
    - DB_HOST=mysql

db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=password
  volumes:
    - /var/lib/mysql
